### PR TITLE
Update AngularFire dependencies

### PR DESCRIPTION
**Pull request by beeman**
This patch makes the project work with the new @angular/fire packages.

I got another branch that upgrades the rest of the project to Angular v7 but there seem to be some issues. I'll push up the WIP branch.

### CODE REVIEW

**Comment by anelad** [comment]
Hi @beeman. Is there any way to use your updated package, since @MurhafSousli is not merged it yet.

**Comment by beeman** [comment]
@anelad I built it locally and installed it to my project using the tarballs.

I will check if I can publish it soon (™️😁)

**Comment by anelad** [comment]
I wrote to @MurhafSousli via Twitter a while ago. I hope he will merge it.

BTW, could you lead me to handle this tarball thing. I'm actually an iOS developer, Node is a bit weird to me.

**Comment by beeman** [comment]
@anelad you can create tarballs (.tgz files) from the build, and these can be installed in a project. I've documented the steps below:

```bash
# clone the repo and run yarn install
# make changes or change to the branch you want to build
# build the project
yarn init-build
# cd into the dist folder
cd dist
# create a tarball for each of the builds (core, manager, photo)
tar cvzf ./ngx-fire-uploader-core.tgz -C ./core .
tar cvzf ./ngx-fire-uploader-manager.tgz -C ./manager .
tar cvzf ./ngx-fire-uploader-photo.tgz -C ./photo .
# copy the tarballs to your application folder 
cp *.tgz ~/my-app/
# cd into your application folder
cd ~/my-app/
# install the tarbals in the project
yarn add file://ngx-fire-uploader-core.tgz file://ngx-fire-uploader-manager.tgz file://ngx-fire-uploader-photo.tgz
```

**Comment by beeman** [comment]
I just merged this PR and published it as 0.9.9. 


```bash
$ npm dist-tag ls @ngx-fire-uploader/core
latest: 0.9.9
$ npm dist-tag ls @ngx-fire-uploader/manager
latest: 0.9.9
$ npm dist-tag ls @ngx-fire-uploader/photo
latest: 0.9.9
```


@anelad could you give it a test please?

**Comment by anelad** [comment]
I've successfully created tarballs from your merge @beeman . But I installed them to my project via npm instead of yarn, I hope it is ok. Thank you very much for your time, effort and concern!

**Comment by anelad** [comment]
Now I'm having css issues.

First, no css rules were installed on items. (Using manager)
So I added `"node_modules/@ngx-fire-uploader/manager/fire-manager.scss"` to angular.json
Now It cannot find svg assets.

Did you have these issues too?

**Comment by beeman** [comment]
@anelad NPM and yarn should both work. 

With that being said, I've published this update to npm so you can just do:

```
npm install @ngx-fire-uploader/core @ngx-fire-uploader/manager @ngx-fire-uploader/photo
```

**Comment by anelad** [comment]
Oww, npm is updated too. Sorry :)

**Pull request merged**
